### ISSUE TITLE
Sample not updated based on 2.0.0 version

### ISSUE THREAD

**Issue by hardikamal** [aerogear/aerogear-push-helloworld#79]
Please update the sample based on 2.0.0 version

**Comment by matzew** [comment]
@hardikamal can you create a ticket on JIRa.jboss.org/browse/AGPUSH ?

**Comment by danielpassos** [comment]
Jira: https://issues.jboss.org/browse/AGDROID-373
PR: https://github.com/aerogear/aerogear-push-helloworld/pull/78
