### ISSUE TITLE
If the app is uninstalled how can the device be unregistered?

### ISSUE THREAD

**Issue by hardikamal** [aerogear/aerogear-push-helloworld#81]

**Comment by edewit** [comment]
Unregister only exists for android have a look here at [why you rarely](http://developer.android.com/google/gcm/adv.html#unreg) need it. And for iOS there is no such thing. What is the issue that you have?

**Comment by danielpassos** [comment]
Hey @hardikamal Could you send us more detail in our [Mailing List](https://lists.jboss.org/mailman/listinfo/aerogear-dev)?
